### PR TITLE
5.0.11

### PR DESCRIPTION
**Pull request by maelle**
#11 
doesn't seem quite right though

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
I've been busily working on this too. Testing my implementation now.

**Comment by maelle** [comment]
oh great!

**Comment by mitchelloharawild** [comment]
Mostly having some issues with the new font-awesome classes.
Working out which ones should be `fas`, `fab`, etc.

**Comment by mitchelloharawild** [comment]
Think I've worked it out now. 
`fas` is for solid icons (most icons), and `fab` is for brands (to get our lovely R icon).

**Comment by maelle** [comment]
Good catch!!

Good occasion to promote the package & ozunconf17!

**Comment by mitchelloharawild** [comment]
That's the plan! :rocket:

**Pull request closed without merging**
